Sprint5 us024 santiago
at-internship/at-sce-ui-qe pull request #4
Opened 2021-05-10 21:16 UTC by Ulises-Santiago-Juarez-AT

2021-05-10 21:33 UTC, ramiroAT requested changes
Ulises I noticed you add a directory to this project named as "US 024-UI-SCE Admin Form Validations Error Handling" could you please remove it? So we can avoid to impact other team members. Then send again your PR.

2021-05-11 16:27 UTC, ramiroAT requested changes
Please remove runcakeTest class from this pull request. Also take a look to one observation for Admin.feature

2021-05-11 16:27 UTC, ramiroAT commented on src/test/resources/Admin.feature
> +When goes to the webpage of Admin for create a user
For this Admin feature Do you consider the posibility to add these five steps as part of the background? I notice you need to call them  for all the scenarios on this feature file.

2021-05-28 14:24 UTC, ramiroAT approved these changes

2021-05-28 14:27 UTC, VillaAT approved these changes
LGTM!

2021-05-28 15:12 UTC, merged